import { MlResearchPanel } from "@/components/ml-research/MlResearchPanel";

export default function MlResearchPage() {
  return (
    <>
      <div className="mb-6">
        <h1 className="text-3xl font-semibold text-white mb-2">ML research &amp; evaluation</h1>
        <p className="text-gray-400 max-w-3xl">
          Assignment deliverables: application-specific data splits, QLoRA fine-tuning, baselines, SQLite +
          Chroma storage, BLEU / ROUGE metrics, and qualitative error analysis — surfaced here from{" "}
          <code className="text-cyan-400">public/ml-results/metrics.json</code> (generated by{" "}
          <code className="text-cyan-400">ml/scripts/evaluate_baselines.py</code>).
        </p>
      </div>
      <MlResearchPanel />
    </>
  );
}
